import Foundation

/// L'assembly de test, produit par **le vrai producteur** (`dotnet build`,
/// net6.0, Release) et non écrit à la main : une fixture de métadonnées
/// rédigée à la main décrit un état qu'aucun compilateur n'émet.
///
/// Son contenu porte délibérément les pièges du format (source en
/// `docs/SOURCES.md` § 6 ter) :
/// - `IEmptyMarker` et `Outer` n'ont **aucun champ** — plage vide ;
/// - `Outer.NestedMode` est le **dernier** TypeDef — la plage de champs
///   d'une dernière ligne se termine au bout de la table, pas à la ligne
///   suivante ;
/// - `LastOwner` est la **dernière** entrée de `PropertyMap` et possède
///   une propriété — même piège côté propriétés ;
/// - `AutoProps` porte des `<X>k__BackingField` non littéraux — un type
///   à champs n'est pas un enum ;
/// - `ModConfig.Hotkey` est typée par un enum d'un **autre** assembly
///   (TypeRef) — le cas `SButton`, à exclure ;
/// - `Thresholds` est un **struct à constantes** : type valeur comme un
///   enum, champs littéraux comme un enum, mais **sans `value__`** —
///   c'est le seul cas qui rend ce marqueur nécessaire, et le filtre
///   `fdLiteral` seul le laisserait passer pour un enum.
///
/// Réponse attendue (oracle `tools/gmcm_options.py`, dnfile) :
/// `Placement`, `Enabled`, `Mode`, `Fallback` — et rien d'autre.
enum FixtureAssembly {
    static var bytes: [UInt8] { Array(Data(base64Encoded: base64)!) }

    static let base64 =
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgB" +
        "TM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAMfMM50AAAAAAAAAAOAA" +
        "IiALATAAABIAAAAGAAAAAAAAcjAAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUA" +
        "ABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAB0wAABPAAAAAEAAADADAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAADkLgAA" +
        "VAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAA" +
        "AC50ZXh0AAAAeBAAAAAgAAAAEgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAADADAAAAQAAAAAQAAAAUAAAAAAAAAAAAAAAA" +
        "AABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAGAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAABRMAAAAAAAAEgAAAAC" +
        "AAUAYCEAAIQNAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4CewEAAAQq" +
        "IgIDfQEAAAQqHgJ7AgAABCoiAgN9AgAABCpKAnIBAABwfQEAAAQCKA0AAAoqHgIoDQAACioeAnsPAAAEKiICA30PAAAEKh4CexAA" +
        "AAQqIgIDfRAAAAQqHgJ7EQAABCoiAgN9EQAABCoeAnsSAAAEKiICA30SAAAEKh4CexMAAAQqIgIDfRMAAAQqHgJ7FAAABCoiAgN9" +
        "FAAABCoeAnsVAAAEKiICA30VAAAEKh4CexYAAAQqIgIDfRYAAAQqHgJ7FwAABCoiAgN9FwAABCpmAhl9EQAABAJyAQAAcH0XAAAE" +
        "AigNAAAKKh4CexgAAAQqIgIDfRgAAAQqOgIXfRgAAAQCKA0AAAoqQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAA" +
        "lAYAACN+AAAABwAA+AQAACNTdHJpbmdzAAAAAPgLAAAEAAAAI1VTAPwLAAAQAAAAI0dVSUQAAAAMDAAAeAEAACNCbG9iAAAAAAAA" +
        "AAIAAAFXHaABCQIAAAD6ATMAFgAAAQAAABEAAAAKAAAAGwAAABwAAAAMAAAADQAAAAsAAAAvAAAAAwAAAAwAAAAYAAAAAQAAAAIA" +
        "AAABAAAAAACcAwEAAAAAAAYAtwIKBAYACQMKBAYAAgLsAw8AKgQAAAYALQI3AwYA8AK3AwYAiQK3AwYARgK3AwYAYwK3AwYA1wK3" +
        "AwYAFgK3AwYAeASrAwYA5wEKBAYAsgOrAwYAqAKrAwYAvwGrAwoAzARKBAAAAAABAAAAAAABAAEAoQAQAMkDTwEAAAEAAQABABAA" +
        "WARPATEAAQABAAEBAACLAU8BOQADAAYAAQEAADkETwE5AAcABgABABAA4ANPATEADAAGAAkBEAD/A08BQQAMAAcAAQAQAC0DTwEx" +
        "AA8ABwABABAA1gNPATEAGAAaAAIBAABsAQAAOQAZAB0AAQBwADcAAQAaAToABgYKADoAVoB/BD0AVoDhAT0AVoDuBD0ABgYKADoA" +
        "VoC6AUEAVoBJAUEAVoBCBEEAVoCYA0EAVoDDBDoAVoBRAzoABgCiBDoAAQDnAEUAAQD/AD0AAQAqAEEAAQBDAEkAAQAxAU0AAQCG" +
        "AFEAAQCfADoAAQBZAFQAAQDQADcAAQC2AD0ABgYKADoAVoC+BEkAVoDHBEkAUCAAAAAAhgiZAVcAAQBYIAAAAACGCKIBEAABAGEg" +
        "AAAAAIYIqgRbAAIAaSAAAAAAhgi0BAEAAgByIAAAAACGGOYDBgADAIUgAAAAAIYY5gMGAAMAjSAAAAAAhghiBF8AAwCVIAAAAACG" +
        "CG0EZAADAJ4gAAAAAIYIhgRqAAQApiAAAAAAhgiUBG8ABACvIAAAAACGCBIAdQAFALcgAAAAAIYIHgB6AAUAwCAAAAAAhghaAYAA" +
        "BgDIIAAAAACGCGMBhQAGANEgAAAAAIYI2ASLAAcA2SAAAAAAhgjjBJAABwDiIAAAAACGCMkBlgAIAOogAAAAAIYI1QGaAAgA8yAA" +
        "AAAAhghWA1sACQD7IAAAAACGCGADAQAJAAQhAAAAAIYIdwGfAAoADCEAAAAAhgiBAaMACgAVIQAAAACGCIQDVwALAB0hAAAAAIYI" +
        "jgMQAAsAJiEAAAAAhhjmAwYADABAIQAAAACGCGoDagAMAEghAAAAAIYIdwNvAAwAUSEAAAAAhhjmAwYADQAAAAEAJwMAAAEAJwMA" +
        "AAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMAAAEAJwMJAOYDAQARAOYDBgAZAOYD" +
        "CgApAOYDEAAxAOYDEAA5AOYDEABBAOYDEABJAOYDEABRAOYDEABZAOYDEABpAOYDBgB5AOYDBgBhAOYDBgAIABAAHgAIABQAIwAI" +
        "ABgAKAAIACAAHgAIACQAIwAIACgAKAAIACwALQAIADAAIwAIADQAMgAIAGgAHgAIAGwAIwAgAFsAIwAhAFsAIwAuAAsA0QAuABMA" +
        "2gAuABsA+QAuACMAAgEuACsAQAEuADMAUAEuADsAXQEuAEMAagEuAEsAQAEuAFMAQAFAAFsAIwBBAFsAIwBgAFsAIwCAAFsAIwCj" +
        "AGMAIwDgAFsAIwAAAVsAIwAgAVsAIwBAAVsAIwBgAVsAIwCAAVsAIwCgAVsAIwDAAVsAIwDgAVsAIwDhAVsAIwAAAlsAIwABAlsA" +
        "IwAgAlsAIwAhAlsAIwBAAlsAIwBBAlsAIwBgAlsAIwBhAlsAIwCAAlsAIwCBAlsAIwCgAlsAIwChAlsAIwDAAlsAIwDBAlsAIwDg" +
        "AlsAIwDhAlsAIwAAA1sAIwABA1sAIwBAA1sAIwBgA1sAIwADAAEACAADAAkADAAAAKYBqAAAALgErAAAAHEEsAAAAJgEtQAAACIA" +
        "ugAAAHIBvwAAAOcExAAAANkByQAAAGQDrAAAAIUBzQAAAJIDqAAAAHsDtQACAAEAAwABAAIAAwACAAMABQABAAQABQACAAcABwAB" +
        "AAgABwACAAkACQABAAoACQACAAsACwABAAwACwACAA0ADQABAA4ADQACAA8ADwABABAADwACABEAEQABABIAEQACABMAEwABABQA" +
        "EwACABUAFQABABYAFQACABcAFwABABgAFwACABoAGQABABsAGQAEgAAAAQAAAAAAAAAAAAAAAABPAQAABgAAAAAAAAAAAAAAFQCr" +
        "AQAAAAABAAAAAAAAAAAAAAAAAEoEAAAAAAoABgAAAAA8TW9kdWxlPgB2YWx1ZV9fAGdldF9FbmFibGVkAHNldF9FbmFibGVkADxF" +
        "bmFibGVkPmtfX0JhY2tpbmdGaWVsZAA8TW9kZT5rX19CYWNraW5nRmllbGQAPFNjYWxlPmtfX0JhY2tpbmdGaWVsZAA8TmFtZT5r" +
        "X19CYWNraW5nRmllbGQAPFZlcmJvc2U+a19fQmFja2luZ0ZpZWxkADxEZXB0aD5rX19CYWNraW5nRmllbGQAPEZhbGxiYWNrPmtf" +
        "X0JhY2tpbmdGaWVsZAA8TGFiZWw+a19fQmFja2luZ0ZpZWxkADxMaW1pdHM+a19fQmFja2luZ0ZpZWxkADxQbGFjZW1lbnQ+a19f" +
        "QmFja2luZ0ZpZWxkADxDb3VudD5rX19CYWNraW5nRmllbGQAPEhvdGtleT5rX19CYWNraW5nRmllbGQAU291bmQARml4dHVyZU1v" +
        "ZABnZXRfTW9kZQBzZXRfTW9kZQBOZXN0ZWRNb2RlAGdldF9TY2FsZQBzZXRfU2NhbGUAUGxhY2VtZW50UnVsZQBnZXRfTmFtZQBz" +
        "ZXRfTmFtZQBTeXN0ZW0uUnVudGltZQBOb25lAFZhbHVlVHlwZQBnZXRfVmVyYm9zZQBzZXRfVmVyYm9zZQBMb29zZQBDb21waWxl" +
        "ckdlbmVyYXRlZEF0dHJpYnV0ZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3" +
        "b3JrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlJbmZvcm1hdGlvbmFsVmVyc2lvbkF0dHJp" +
        "YnV0ZQBBc3NlbWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUARmxhZ3NBdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0" +
        "dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmls" +
        "aXR5QXR0cmlidXRlAHZhbHVlAE1vZENvbmZpZwBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAEhpZ2gAZ2V0X0RlcHRoAHNldF9E" +
        "ZXB0aABnZXRfRmFsbGJhY2sAc2V0X0ZhbGxiYWNrAGdldF9MYWJlbABzZXRfTGFiZWwAQWxsAEZpeHR1cmVNb2QuZGxsAFN5c3Rl" +
        "bQBFbnVtAFN5c3RlbS5SZWZsZWN0aW9uAElFbXB0eU1hcmtlcgBMYXN0T3duZXIAT3V0ZXIALmN0b3IAU3lzdGVtLkRpYWdub3N0" +
        "aWNzAFRocmVzaG9sZHMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBEZWJ1Z2dpbmdNb2RlcwBGZWF0dXJlcwBWaXN1" +
        "YWxzAEV4dGVybmFsRW51bXMAQXV0b1Byb3BzAGdldF9MaW1pdHMAc2V0X0xpbWl0cwBPYmplY3QAU3RyaWN0AGdldF9QbGFjZW1l" +
        "bnQAc2V0X1BsYWNlbWVudABDdXJyZW50AGdldF9Db3VudABzZXRfQ291bnQARmFzdABMb3cAU2xvdwBFeHRlcm5hbEtleQBnZXRf" +
        "SG90a2V5AHNldF9Ib3RrZXkAQW5hcmNoeQAAAAABAADJmjv+7qORQaeYxQTNo4c5AAQgAQEIAyAAAQUgAQEREQQgAQEOCLA/X38R" +
        "1Qo6BAAAAAAEAQAAAAQCAAAABAMAAAAECQAAAAIGDgIGCAMGERADBhEUAwYRHAMGESgDBhFFAgYCAgYNAyAADgMgAAgEIAARHAUg" +
        "AQERHAQgABEQBSABAREQBCAAERQFIAEBERQEIAARKAUgAQERKAQgABFFBSABARFFAyAAAgQgAQECAyAADQQgAQENAygADgMoAAgE" +
        "KAARHAQoABEQBCgAERQEKAARKAQoABFFAygAAgMoAA0IAQAIAAAAAAAeAQABAFQCFldyYXBOb25FeGNlcHRpb25UaHJvd3MBCAEA" +
        "AgAAAAAAPQEAGC5ORVRDb3JlQXBwLFZlcnNpb249djYuMAEAVA4URnJhbWV3b3JrRGlzcGxheU5hbWUILk5FVCA2LjAPAQAKRml4" +
        "dHVyZU1vZAAADAEAB1JlbGVhc2UAAAwBAAcxLjAuMC4wAAAKAQAFMS4wLjAAAAAAAAAAAADJUEr6AAFNUAIAAAC+AAAAOC8AADgR" +
        "AAAAAAAAAAAAAAEAAAATAAAAJwAAAPYvAAD2EQAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAFJTRFOmqHFYaB2rTKSeChNB" +
        "oPUqAQAAAC9wcml2YXRlL3RtcC9jbGF1ZGUtNTAxLy1Vc2Vycy1kYXZpZGJhdWRvaW4tRG9jdW1lbnRzLUdpdEh1Yi1TdGFySHVi" +
        "VEgvZGExNGQ4ZTctYjA4Yy00YWEzLThkZjQtNDdkNTEwNGVjYTI1L3NjcmF0Y2hwYWQvZml4dHVyZS9tYWluL29iai9SZWxlYXNl" +
        "L25ldDYuMC9GaXh0dXJlTW9kLnBkYgBTSEEyNTYApqhxWGgdq1zkngoTQaD1KslQSvpGjar2h3nhMzrLurhFMAAAAAAAAAAAAABf" +
        "MAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUTAAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAAAAAA/yUA" +
        "IAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAEAAAABgAAIAAAAAAAAAAAAAAAAAAAAEAAQAAADAAAIAAAAAAAAAA" +
        "AAAAAAAAAAEAAAAAAEgAAABYQAAA1AIAAAAAAAAAAAAA1AI0AAAAVgBTAF8AVgBFAFIAUwBJAE8ATgBfAEkATgBGAE8AAAAAAL0E" +
        "7/4AAAEAAAABAAAAAAAAAAEAAAAAAD8AAAAAAAAABAAAAAIAAAAAAAAAAAAAAAAAAABEAAAAAQBWAGEAcgBGAGkAbABlAEkAbgBm" +
        "AG8AAAAAACQABAAAAFQAcgBhAG4AcwBsAGEAdABpAG8AbgAAAAAAAACwBDQCAAABAFMAdAByAGkAbgBnAEYAaQBsAGUASQBuAGYA" +
        "bwAAABACAAABADAAMAAwADAAMAA0AGIAMAAAADYACwABAEMAbwBtAHAAYQBuAHkATgBhAG0AZQAAAAAARgBpAHgAdAB1AHIAZQBN" +
        "AG8AZAAAAAAAPgALAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAAEYAaQB4AHQAdQByAGUATQBvAGQAAAAAADAA" +
        "CAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAAMQAuADAALgAwAC4AMAAAAD4ADwABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBl" +
        "AAAARgBpAHgAdAB1AHIAZQBNAG8AZAAuAGQAbABsAAAAAAAoAAIAAQBMAGUAZwBhAGwAQwBvAHAAeQByAGkAZwBoAHQAAAAgAAAA" +
        "RgAPAAEATwByAGkAZwBpAG4AYQBsAEYAaQBsAGUAbgBhAG0AZQAAAEYAaQB4AHQAdQByAGUATQBvAGQALgBkAGwAbAAAAAAANgAL" +
        "AAEAUAByAG8AZAB1AGMAdABOAGEAbQBlAAAAAABGAGkAeAB0AHUAcgBlAE0AbwBkAAAAAAAwAAYAAQBQAHIAbwBkAHUAYwB0AFYA" +
        "ZQByAHMAaQBvAG4AAAAxAC4AMAAuADAAAAA4AAgAAQBBAHMAcwBlAG0AYgBsAHkAIABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAw" +
        "AC4AMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAwA" +
        "AAB0MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
}
