import Foundation
import Cocoa
import SwiftUI

extension Dictionary where Key == String {
    func caseInsensitiveValue(forKey key: String) -> Value? {
        if let value = self[key] { return value }
        let lowerKey = key.lowercased()
        if let match = self.first(where: { $0.key.lowercased() == lowerKey }) {
            return match.value
        }
        return nil
    }
}

struct ModDependency: Equatable {
    let uniqueId: String
    let isRequired: Bool
}

struct ModItem: Identifiable, Equatable {
    var id: String { folderName }
    let uniqueId: String
    let name: String
    let folderName: String
    let version: String
    let author: String
    let description: String
    let nexusUrl: String
    var isEnabled: Bool
    let dependencies: [ModDependency]
    var children: [ModItem]?
    var isGroup: Bool = false
}

struct ModUpdateInfo: Identifiable, Equatable {
    var id: String { name }
    let name: String
    let version: String
    let url: String
}

struct ThaiTranslationMod: Identifiable, Equatable {
    var id: String { name }
    let name: String
    let author: String
    let version: String
    let status: String
    let url: String
    let nexusUrl: String
    var isInstalled: Bool = false
    var isOriginalModInstalled: Bool = false
    
    func translatedStatus(vm: StarHubTHViewModel) -> String {
        if status.contains("เสร็จสมบูรณ์") {
            return "✅ " + vm.L(L10n.ThaiHub.completed)
        } else if status.contains("รอแปล") {
            return "⏳ " + vm.L(L10n.ThaiHub.waitingTranslation)
        }
        return status
    }
    
    func installationStatusText(vm: StarHubTHViewModel) -> String {
        if isInstalled {
            return vm.L(L10n.ThaiHub.installed)
        } else if isOriginalModInstalled {
            return vm.L(L10n.ThaiHub.availableDownload)
        } else {
            return vm.L(L10n.ThaiHub.missingOriginal)
        }
    }
}

// MARK: - Log Entry Model
enum LogLevel: String, CaseIterable {
    case info    = "INFO"
    case warning = "WARN"
    case error   = "ERROR"
    case smapi   = "SMAPI"   // TRACE/DEBUG from SMAPI file

    var color: Color {
        switch self {
        case .info:    return .primary
        case .warning: return .orange
        case .error:   return .red
        case .smapi:   return .blue
        }
    }

    var icon: String {
        switch self {
        case .info:    return "info.circle"
        case .warning: return "exclamationmark.triangle"
        case .error:   return "xmark.octagon"
        case .smapi:   return "terminal"
        }
    }
}

enum LogSource {
    case app    // generated by StarHubTH itself
    case smapi  // loaded from SMAPI-latest.txt
}

struct LogEntry: Identifiable {
    let id = UUID()
    let timestamp: String
    let message: String
    let level: LogLevel
    let source: LogSource
    var modName: String? = nil
}

enum SaveViewMode: String, Codable {
    case list
    case grid
}

enum SaveSortOption: String, Codable {
    case name
    case lastPlayed
    case money
}

class StarHubTHViewModel: ObservableObject {
    @Published var saveViewMode: SaveViewMode = .list
    @Published var saveSortOption: SaveSortOption = .lastPlayed
    @Published var saveFilterTag: String = ""

    @Published var gameDir: String = "" {
        didSet {
            UserDefaults.standard.set(gameDir, forKey: "gameDir")
            self.refresh()
        }
    }
    
    @Published var outOfDateMods: [ModUpdateInfo] = []
    @Published var smapiErrors: [String] = []
    @Published var showSmapiAlerts: Bool = false
    
    @Published var smapiInstalledVersion: String? = nil   // nil = not installed
    @Published var mods: [ModItem] = []
    
    // Thai Translation Hub State
    @Published var thaiTranslations: [ThaiTranslationMod] = []
    @Published var viewingThaiMod: ThaiTranslationMod? = nil
    
    @Published var logOutput: String = ""
    @Published var logEntries: [LogEntry] = []
    private var smapiLogFileHandle: FileHandle? = nil
    @Published var smapiLogTimer: Timer? = nil
    @Published var alertMessage: String = ""
    @Published var showAlert: Bool = false
    @Published var isThaiTranslationInstalled: Bool = false
    
    @Published var saves: [SaveGameInfo] = []
    @Published var editingSave: SaveGameInfo? = nil
    @Published var viewingSaveTimeline: SaveGameInfo? = nil
    
    @Published var saveToDuplicate: SaveGameInfo? = nil
    @Published var backupToBranch: SaveBackup? = nil
    
    @Published var steamUsername: String = ""
    @Published var steamAvatarPath: String? = nil
    
    private static let supportedLanguages = Set(["en", "th"])
    private static func normalizedLanguage(_ language: String?) -> String {
        guard let language, supportedLanguages.contains(language) else { return defaultLanguage }
        return language
    }
    private static var defaultLanguage: String {
        Locale.preferredLanguages.contains { $0.lowercased().hasPrefix("th") } ? "th" : "en"
    }
    
    @Published var currentLanguage: String = StarHubTHViewModel.normalizedLanguage(UserDefaults.standard.string(forKey: "currentLanguage")) {
        didSet {
            if !Self.supportedLanguages.contains(currentLanguage) {
                currentLanguage = "en"
                return
            }
            UserDefaults.standard.set(currentLanguage, forKey: "currentLanguage")
            UserDefaults.standard.set([currentLanguage], forKey: "AppleLanguages")
            UserDefaults.standard.synchronize()
        }
    }
    
    
    @Published var modProfiles: [ModProfile] = []
    @Published var activeProfileId: UUID? = nil

    /// When true, toggling a mod also cascades to its dependencies / dependents.
    /// Persisted in UserDefaults so SettingsView @AppStorage stays in sync.
    var chainToggleDependencies: Bool {
        get { UserDefaults.standard.object(forKey: "chainToggleDependencies") as? Bool ?? true }
        set { UserDefaults.standard.set(newValue, forKey: "chainToggleDependencies") }
    }
    
    let smapiInstaller = SmapiInstaller()
    
    init() {
        // Force sync AppleLanguages with currentLanguage at startup
        let savedLang = Self.normalizedLanguage(UserDefaults.standard.string(forKey: "currentLanguage"))
        currentLanguage = savedLang
        UserDefaults.standard.set([savedLang], forKey: "AppleLanguages")
        
        // Automatically retrieve saved game path, or attempt to find the default Steam path on Mac
        let savedPath = UserDefaults.standard.string(forKey: "gameDir") ?? ""
        if !savedPath.isEmpty && FileManager.default.fileExists(atPath: savedPath) {
            self.gameDir = savedPath
        } else {
            self.gameDir = self.detectDefaultGameDir()
        }
        self.refresh()
        self.loadProfiles()
        if self.steamUsername.isEmpty {
            self.steamUsername = L(L10n.VM.defaultFarmerName)
        }
        // Startup marker — confirms LogsView is receiving entries
        log("StarHubTH started", level: .info)
    }
    
    func detectDefaultGameDir() -> String {
        let home = NSHomeDirectory()
        let steamPath = "\(home)/Library/Application Support/Steam/steamapps/common/Stardew Valley/Contents/MacOS"
        if FileManager.default.fileExists(atPath: steamPath) {
            return steamPath
        }
        
        let gogPath = "/Applications/Stardew Valley.app/Contents/MacOS"
        if FileManager.default.fileExists(atPath: gogPath) {
            return gogPath
        }
        
        return ""
    }
    
    func selectGameDir() {
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        if panel.runModal() == .OK {
            self.gameDir = panel.url?.path ?? ""
            UserDefaults.standard.set(self.gameDir, forKey: "gameDir")
            scanMods()
            checkSmapiVersion()
        }
    }
    
    // Helper to force localization using the currently selected language bundle
    func localizedString(for key: String) -> String {
        // Build the lproj URL directly from resourceURL (more reliable for swiftc-built apps)
        if let resourceURL = Bundle.main.resourceURL {
            let lprojURL = resourceURL.appendingPathComponent("\(currentLanguage).lproj")
            if let bundle = Bundle(url: lprojURL) {
                // Must call localizedString directly on the bundle object
                let result = bundle.localizedString(forKey: key, value: "__MISSING__", table: nil)
                if result != "__MISSING__" { return result }
            }
        }
        // Last resort: return key so missing translations are visible
        return key
    }

    /// Typed-key shorthand. Prefer this over localizedString(for:) with raw strings.
    /// Example: vm.L(L10n.Mods.enabled)
    func L(_ key: String) -> String {
        localizedString(for: key)
    }
    
    func refresh() {
        self.checkSmapiVersion()
        self.scanMods()
        self.reloadSaves()
        self.fetchSteamUser()
    }
    
    func fetchSteamUser() {
        let home = NSHomeDirectory()
        let vdfPath = "\(home)/Library/Application Support/Steam/config/loginusers.vdf"
        guard let content = try? String(contentsOfFile: vdfPath, encoding: .utf8) else { return }
        
        // Very basic VDF parsing
        var currentSteamID = ""
        var personaName = ""
        
        let lines = content.components(separatedBy: .newlines)
        for line in lines {
            let tLine = line.trimmingCharacters(in: .whitespacesAndNewlines)
            if tLine.hasPrefix("\"7656") {
                currentSteamID = tLine.replacingOccurrences(of: "\"", with: "")
            }
            if tLine.hasPrefix("\"PersonaName\"") {
                let parts = tLine.components(separatedBy: "\"")
                if parts.count >= 4 { personaName = parts[3] }
            }
            if tLine.hasPrefix("\"MostRecent\"") && tLine.contains("\"1\"") {
                break
            }
        }
        
        if !personaName.isEmpty {
            self.steamUsername = personaName
        } else {
            let defaultName = NSFullUserName().components(separatedBy: " ").first ?? ""
            self.steamUsername = defaultName.isEmpty ? L(L10n.VM.defaultFarmerName) : defaultName
        }
        
        if !currentSteamID.isEmpty {
            let avatarPathPng = "\(home)/Library/Application Support/Steam/config/avatarcache/\(currentSteamID).png"
            let avatarPathJpg = "\(home)/Library/Application Support/Steam/config/avatarcache/\(currentSteamID).jpg"
            if FileManager.default.fileExists(atPath: avatarPathPng) {
                self.steamAvatarPath = avatarPathPng
            } else if FileManager.default.fileExists(atPath: avatarPathJpg) {
                self.steamAvatarPath = avatarPathJpg
            }
        }
    }
    
    func checkSmapiVersion() {
        guard !gameDir.isEmpty else {
            self.smapiInstalledVersion = nil
            return
        }
        self.smapiInstalledVersion = SmapiInstaller.getInstalledVersion(gameDir: gameDir)
    }
    
    func scanMods() {
        guard !gameDir.isEmpty else {
            self.mods = []
            return
        }
        
        let fm = FileManager.default
        let modsPath = (gameDir as NSString).appendingPathComponent("Mods")
        let disabledModsPath = (gameDir as NSString).appendingPathComponent("Mods_disabled")
        
        var scannedMods: [ModItem] = []
        
        // Helper to parse a folder containing manifest.json
        func parseModFolder(at path: String, relativePath: String, isEnabled: Bool) -> ModItem? {
            let manifestPath = (path as NSString).appendingPathComponent("manifest.json")
            guard fm.fileExists(atPath: manifestPath) else { return nil }
            
            var name = (path as NSString).lastPathComponent
            var uniqueId = ""
            var version = "Unknown"
            var author = "Unknown"
            var description = ""
            var nexusUrl = ""
            var dependencies: [ModDependency] = []
            
            if let rawData = try? Data(contentsOf: URL(fileURLWithPath: manifestPath)),
               let rawString = String(data: rawData, encoding: .utf8) {
                
                // Strip block comments (/* ... */) often added by ModManifestBuilder
                let cleanString = rawString.replacingOccurrences(of: "/\\*[\\s\\S]*?\\*/", with: "", options: .regularExpression)
                
                var options: JSONSerialization.ReadingOptions = []
                if #available(macOS 12.0, *) {
                    options.insert(.json5Allowed)
                }
                
                if let data = cleanString.data(using: .utf8),
                   let json = try? JSONSerialization.jsonObject(with: data, options: options) as? [String: Any] {
                    
                    if let mName = json.caseInsensitiveValue(forKey: "Name") as? String { name = mName }
                if let mUniqueId = json.caseInsensitiveValue(forKey: "UniqueID") as? String { uniqueId = mUniqueId }
                
                let mVer = json.caseInsensitiveValue(forKey: "Version")
                if let vStr = mVer as? String { 
                    version = vStr 
                } else if let vDict = mVer as? [String: Any] {
                    let major = vDict.caseInsensitiveValue(forKey: "MajorVersion") as? Int ?? 1
                    let minor = vDict.caseInsensitiveValue(forKey: "MinorVersion") as? Int ?? 0
                    let patch = vDict.caseInsensitiveValue(forKey: "PatchVersion") as? Int ?? 0
                    version = "\(major).\(minor).\(patch)"
                }
                
                if let mAuthor = json.caseInsensitiveValue(forKey: "Author") as? String { author = mAuthor }
                if let mDesc = json.caseInsensitiveValue(forKey: "Description") as? String { description = mDesc }
                
                if let deps = json.caseInsensitiveValue(forKey: "Dependencies") as? [[String: Any]] {
                    for dep in deps {
                        if let depId = dep.caseInsensitiveValue(forKey: "UniqueID") as? String {
                            let isReq = dep.caseInsensitiveValue(forKey: "IsRequired") as? Bool ?? true
                            dependencies.append(ModDependency(uniqueId: depId, isRequired: isReq))
                        }
                    }
                }
                
                if let updateKeys = json.caseInsensitiveValue(forKey: "UpdateKeys") as? [String] {
                    for key in updateKeys {
                        if key.lowercased().hasPrefix("nexus:") {
                            let id = key.replacingOccurrences(of: "nexus:", with: "", options: .caseInsensitive)
                            nexusUrl = "https://www.nexusmods.com/stardewvalley/mods/\(id.trimmingCharacters(in: .whitespacesAndNewlines))"
                            break
                        }
                    }
                }
            }
        }
            
            return ModItem(
                uniqueId: uniqueId,
                name: name,
                folderName: relativePath.isEmpty ? (path as NSString).lastPathComponent : relativePath,
                version: version,
                author: author,
                description: description,
                nexusUrl: nexusUrl,
                isEnabled: isEnabled,
                dependencies: dependencies
            )
        }
        
        // Helper to recursively scan folders for manifest.json and group them
        func scanFolderForMods(at path: String, isEnabled: Bool) {
            let url = URL(fileURLWithPath: path)
            var groups: [String: [ModItem]] = [:]
            var ungrouped: [ModItem] = []
            
            if let enumerator = fm.enumerator(at: url, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]) {
                for case let fileURL as URL in enumerator {
                    if fileURL.lastPathComponent.lowercased() == "manifest.json" {
                        let modFolderURL = fileURL.deletingLastPathComponent()
                        let relativePath = modFolderURL.path.replacingOccurrences(of: url.path, with: "").trimmingCharacters(in: CharacterSet(charactersIn: "/"))
                        if let mod = parseModFolder(at: modFolderURL.path, relativePath: relativePath, isEnabled: isEnabled) {
                            
                            // Determine top-level folder
                            let pathComponents = relativePath.components(separatedBy: "/")
                            
                            if pathComponents.count > 1, let topFolder = pathComponents.first, !topFolder.isEmpty {
                                groups[topFolder, default: []].append(mod)
                            } else {
                                ungrouped.append(mod)
                            }
                        }
                    }
                }
            }
            
            scannedMods.append(contentsOf: ungrouped)
            
            for (groupName, modsInGroup) in groups {
                if modsInGroup.count == 1 {
                    scannedMods.append(modsInGroup[0])
                } else {
                    let groupMod = ModItem(
                        uniqueId: "",
                        name: groupName,
                        folderName: groupName,
                        version: "",
                        author: "Group",
                        description: "\(modsInGroup.count) mods",
                        nexusUrl: "",
                        isEnabled: isEnabled,
                        dependencies: [],
                        children: modsInGroup,
                        isGroup: true
                    )
                    scannedMods.append(groupMod)
                }
            }
        }
        
        // Scan enabled mods folder
        if fm.fileExists(atPath: modsPath) {
            scanFolderForMods(at: modsPath, isEnabled: true)
        }
        
        // Scan disabled mods folder
        if fm.fileExists(atPath: disabledModsPath) {
            scanFolderForMods(at: disabledModsPath, isEnabled: false)
        }
        
        parseSMAPILog()
            
        DispatchQueue.main.async {
            self.mods = scannedMods.sorted { 
                if $0.isGroup != $1.isGroup {
                    return $0.isGroup 
                }
                return $0.name.lowercased() < $1.name.lowercased() 
            }
            if self.selectedMod == nil, let first = self.mods.first {
                self.selectedMod = first
            }
            self.isThaiTranslationInstalled = scannedMods.contains {
                ($0.folderName.lowercased() == "stardew valley - thai" ||
                $0.name.localizedCaseInsensitiveContains("thai")) && $0.isEnabled
            }
        }
    }
    
    // Parses the SMAPI-latest.txt log for updates and errors
    func parseSMAPILog() {
        guard !gameDir.isEmpty else { return }
        
        let homeDir = FileManager.default.homeDirectoryForCurrentUser.path
        let logPath = (homeDir as NSString).appendingPathComponent(".config/StardewValley/ErrorLogs/SMAPI-latest.txt")
        guard FileManager.default.fileExists(atPath: logPath),
              let logContent = try? String(contentsOfFile: logPath, encoding: .utf8) else {
            DispatchQueue.main.async {
                self.outOfDateMods = []
                self.smapiErrors = []
            }
            return
        }
        
        var updates: [ModUpdateInfo] = []
        var errors: [String] = []
        
        let lines = logContent.components(separatedBy: .newlines)
        var isParsingUpdates = false
        var isParsingErrors = false
        
        for line in lines {
            // Check for Updates
            if line.contains("You can update") {
                isParsingUpdates = true
                continue
            }
            if isParsingUpdates {
                if line.contains("ALERT SMAPI") && line.contains("https://") {
                    // Example: [12:00:00 ALERT SMAPI]    Content Patcher 2.0.0: https://smapi.io/mods#Content_Patcher
                    let parts = line.components(separatedBy: "ALERT SMAPI]")
                    if parts.count > 1 {
                        let infoString = parts[1].trimmingCharacters(in: .whitespaces)
                        let split = infoString.components(separatedBy: ": https://")
                        if split.count == 2 {
                            let nameAndVersion = split[0]
                            let url = "https://" + split[1]
                            
                            // Naive split by last space for version
                            let nvSplit = nameAndVersion.components(separatedBy: " ")
                            let version = nvSplit.last ?? ""
                            let name = nvSplit.dropLast().joined(separator: " ")
                            
                            updates.append(ModUpdateInfo(name: name, version: version, url: url))
                        }
                    }
                } else if !line.contains("ALERT SMAPI") {
                    // Reached end of alert block
                    isParsingUpdates = false
                }
            }
            
            // Check for Errors (Skipped mods or general red text)
            if line.contains("ERROR SMAPI") {
                if line.contains("Skipped mods") {
                    isParsingErrors = true
                    continue
                }
                
                if isParsingErrors {
                    if line.contains("-------------------------") || line.contains("These mods could not be added") {
                        continue
                    }
                    if line.contains("WARN ") || line.contains("INFO ") || line.contains("TRACE ") || line.contains("DEBUG ") {
                        isParsingErrors = false
                    } else {
                        let parts = line.components(separatedBy: "ERROR SMAPI]")
                        if parts.count > 1 {
                            let msg = parts[1].trimmingCharacters(in: .whitespaces)
                            if !msg.isEmpty {
                                errors.append(msg)
                            }
                        }
                    }
                } else {
                    // General error line not in "Skipped mods"
                    if !line.contains("Skipped mods") && !line.contains("-------------------------") {
                        let parts = line.components(separatedBy: "ERROR")
                        if parts.count > 1 {
                            let msg = parts[1].trimmingCharacters(in: .whitespaces)
                            // Filter out known empty or structural lines
                            if msg.hasPrefix("SMAPI]") {
                                let actualMsg = msg.replacingOccurrences(of: "SMAPI]", with: "").trimmingCharacters(in: .whitespaces)
                                if !actualMsg.isEmpty {
                                    errors.append(actualMsg)
                                }
                            }
                        }
                    }
                }
            } else if isParsingErrors && (line.contains("WARN ") || line.contains("INFO ") || line.contains("TRACE ") || line.contains("DEBUG ")) {
                isParsingErrors = false
            }
        }
        
        // Remove duplicates and limit error messages
        let uniqueErrors = Array(NSOrderedSet(array: errors)).prefix(10).map { $0 as! String }
        
        DispatchQueue.main.async {
            self.outOfDateMods = updates
            self.smapiErrors = uniqueErrors
        }
    }
    
    // Returns missing required unique IDs for a given mod
    func getMissingDependencies(for mod: ModItem) -> [String] {
        var allUniqueIds = Set<String>()
        for m in mods {
            if m.isGroup, let children = m.children {
                for c in children {
                    allUniqueIds.insert(c.uniqueId.lowercased())
                }
            } else {
                allUniqueIds.insert(m.uniqueId.lowercased())
            }
        }
        
        return mod.dependencies.compactMap { dep in
            guard dep.isRequired else { return nil }
            return allUniqueIds.contains(dep.uniqueId.lowercased()) ? nil : dep.uniqueId
        }
    }
    
    // Toggle Mod Status (Enabled / Disabled)
    func toggleMod(_ mod: ModItem) {
        // Helper to find the top-level folder that contains a given uniqueId
        func getTopLevelFolder(for uniqueId: String) -> String? {
            for m in self.mods {
                if !m.isGroup && m.uniqueId.caseInsensitiveCompare(uniqueId) == .orderedSame {
                    return m.folderName
                } else if m.isGroup, let children = m.children {
                    if children.contains(where: { $0.uniqueId.caseInsensitiveCompare(uniqueId) == .orderedSame }) {
                        return m.folderName
                    }
                }
            }
            return nil
        }
        
        // Helper to get all dependencies of a top-level folder (including its children)
        func getDependencies(for folderName: String) -> [ModDependency] {
            guard let m = self.mods.first(where: { $0.folderName == folderName }) else { return [] }
            if m.isGroup, let children = m.children {
                return children.flatMap { $0.dependencies }
            } else {
                return m.dependencies
            }
        }
        
        var foldersToToggle: Set<String> = [mod.folderName]
        let targetState = !mod.isEnabled // True if we are enabling, false if disabling
        
        if chainToggleDependencies {
            if targetState == true {
                // Enabling: recursively enable all REQUIRED dependencies
                var queue = [mod.folderName]
                while !queue.isEmpty {
                    let currentFolder = queue.removeFirst()
                    let deps = getDependencies(for: currentFolder)
                    
                    for dep in deps where dep.isRequired {
                        if let depFolder = getTopLevelFolder(for: dep.uniqueId) {
                            let isDepFolderEnabled = self.mods.first(where: { $0.folderName == depFolder })?.isEnabled ?? false
                            if !isDepFolderEnabled && !foldersToToggle.contains(depFolder) {
                                foldersToToggle.insert(depFolder)
                                queue.append(depFolder)
                            }
                        }
                    }
                }
            } else {
                // Disabling: recursively disable all enabled mods that REQUIRE this mod
                var queue = [mod.folderName]
                while !queue.isEmpty {
                    let currentFolder = queue.removeFirst()
                    
                    var providedUniqueIds: [String] = []
                    if let m = self.mods.first(where: { $0.folderName == currentFolder }) {
                        if m.isGroup, let children = m.children {
                            providedUniqueIds = children.map { $0.uniqueId }
                        } else {
                            providedUniqueIds = [m.uniqueId]
                        }
                    }
                    
                    for otherMod in self.mods where otherMod.isEnabled && !foldersToToggle.contains(otherMod.folderName) {
                        let otherDeps = getDependencies(for: otherMod.folderName)
                        let requiresCurrent = otherDeps.contains { dep in
                            dep.isRequired && providedUniqueIds.contains { $0.caseInsensitiveCompare(dep.uniqueId) == .orderedSame }
                        }
                        if requiresCurrent {
                            foldersToToggle.insert(otherMod.folderName)
                            queue.append(otherMod.folderName)
                        }
                    }
                }
            }
        }
        // else: chainToggleDependencies == false → only toggle the single mod itself
        
        let fm = FileManager.default
        let modsPath = (gameDir as NSString).appendingPathComponent("Mods")
        let disabledModsPath = (gameDir as NSString).appendingPathComponent("Mods_disabled")
        var anyMoved = false
        
        for folderName in foldersToToggle {
            guard let m = self.mods.first(where: { $0.folderName == folderName }) else { continue }
            if m.isEnabled == targetState { continue }
            
            let srcPath = ((m.isEnabled ? modsPath : disabledModsPath) as NSString).appendingPathComponent(m.folderName)
            let destFolder = m.isEnabled ? disabledModsPath : modsPath
            let destPath = ((destFolder as NSString).appendingPathComponent(m.folderName) as String)
            
            do {
                let destParent = (destPath as NSString).deletingLastPathComponent
                if !fm.fileExists(atPath: destParent) {
                    try fm.createDirectory(atPath: destParent, withIntermediateDirectories: true, attributes: nil)
                }
                if fm.fileExists(atPath: destPath) {
                    try fm.removeItem(atPath: destPath)
                }
                try fm.moveItem(atPath: srcPath, toPath: destPath)
                anyMoved = true
            } catch {
                print("Failed to toggle \(m.name): \(error.localizedDescription)")
            }
        }
        
        if anyMoved {
            log("\(targetState ? L(L10n.Mods.enabled) : L(L10n.Mods.disabled)): \(mod.name)\(foldersToToggle.count > 1 ? " + Dependencies" : "")")
            self.scanMods()
            self.syncActiveProfileIds()
        }
    }
    
    // Install SMAPI via Installer Helper
    func installSmapi() {
        smapiInstaller.install(gameDir: gameDir) { success, msg in
            self.checkSmapiVersion()
            self.showModal(message: self.L(msg))
            self.log(self.L(msg))
        }
    }
    
    // Uninstall SMAPI
    func uninstallSmapi() {
        smapiInstaller.uninstall(gameDir: gameDir) { success, msg in
            self.checkSmapiVersion()
            self.showModal(message: self.L(msg))
            self.log(self.L(msg))
        }
    }
    
    @Published var selectedMod: ModItem? = nil {
        didSet {
            if let mod = selectedMod, selectedModID != mod.folderName {
                selectedModID = mod.folderName
            }
        }
    }
    @Published var selectedModID: String? = nil {
        didSet {
            if let id = selectedModID, selectedMod?.folderName != id {
                selectedMod = mods.first { $0.folderName == id }
            }
        }
    }
    @Published var isPlayingGame: Bool = false
    @Published var selectedProfile: String = "SMAPI"
    
    // Launch Stardew Valley (with selected profile)
    func launchGame() {
        guard !gameDir.isEmpty else {
            showModal(message: L(L10n.Settings.gameDirNotSet))
            return
        }
        
        let profile = UserDefaults.standard.string(forKey: "launchProfile") ?? "SMAPI"
        let closeAfter = UserDefaults.standard.bool(forKey: "closeAfterLaunch")
        
        self.isPlayingGame = true
        
        let originalPath = (gameDir as NSString).appendingPathComponent("StardewValley-original")
        
        if profile == "Vanilla" && FileManager.default.fileExists(atPath: originalPath) {
            log(L(L10n.VM.launchingVanilla))
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/bin/bash")
            process.arguments = [originalPath]
            process.currentDirectoryURL = URL(fileURLWithPath: gameDir)
            do {
                try process.run()
                log(L(L10n.VM.launchVanillaSuccess))
                if closeAfter { NSApplication.shared.terminate(nil) }
            } catch {
                log(String(format: L(L10n.VM.launchVanillaError), error.localizedDescription))
                showModal(message: L(L10n.VM.cannotStartVanilla))
            }
        } else {
            log(L(L10n.VM.launchingSmapi))
            if let steamURL = URL(string: "steam://run/413150") {
                if NSWorkspace.shared.open(steamURL) {
                    log(L(L10n.VM.launchSteamSuccess))
                    startSmapiLogWatcher()
                    if closeAfter { NSApplication.shared.terminate(nil) }
                    DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
                        self.isPlayingGame = false
                    }
                    return
                }
            }
            
        let nsPath = gameDir as NSString
        var appPath = gameDir
        if nsPath.contains(".app") {
            var current = nsPath
            while current.length > 0 && !current.lastPathComponent.hasSuffix(".app") {
                current = current.deletingLastPathComponent as NSString
            }
            if current.length > 0 {
                appPath = current as String
            }
        }
        
        // Fallback: Open app directly
        let appURL = URL(fileURLWithPath: appPath)
            if NSWorkspace.shared.open(appURL) {
                log(L(L10n.VM.launchDirectSuccess))
                startSmapiLogWatcher()
                if closeAfter { NSApplication.shared.terminate(nil) }
            } else {
                log(L(L10n.VM.cannotStartDirect))
                showModal(message: L(L10n.VM.cannotStartGame))
            }
        }
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 4) {
            self.isPlayingGame = false
        }
    }
    
    func log(_ message: String, level: LogLevel = .info) {
        let formatter = DateFormatter()
        formatter.dateFormat = "HH:mm:ss"
        let timestamp = formatter.string(from: Date())
        let entry = LogEntry(timestamp: timestamp, message: message, level: level, source: .app)

        if Thread.isMainThread {
            logEntries.append(entry)
            logOutput += "[\(timestamp)] \(message)\n"
        } else {
            DispatchQueue.main.async {
                self.logEntries.append(entry)
                self.logOutput += "[\(timestamp)] \(message)\n"
            }
        }
    }

    // MARK: - SMAPI Real-time Log Reader

    // MARK: - SMAPI Log Reader

    /// Load SMAPI-latest.txt once when Logs tab is opened.
    /// No live polling — SMAPI doesn't flush continuously anyway.
    func loadSmapiLog() {
        let path = smapiLogPath
        guard FileManager.default.fileExists(atPath: path),
              let data = FileManager.default.contents(atPath: path),
              let text = String(data: data, encoding: .utf8) else { return }

        let lines = text.components(separatedBy: .newlines)
        var entries: [LogEntry] = []

        for line in lines {
            // SMAPI format: [HH:MM:SS LEVEL  Context] message
            // (double space between level and context is intentional in SMAPI)
            if line.hasPrefix("[") {
                guard let bracketEnd = line.firstIndex(of: "]") else {
                    // malformed — skip
                    continue
                }

                let header = String(line[line.index(after: line.startIndex)..<bracketEnd])
                // Split by whitespace, filter empty (handles double space)
                let headerParts = header.components(separatedBy: .whitespaces).filter { !$0.isEmpty }
                // headerParts: [0]=HH:MM:SS, [1]=LEVEL, [2+]=Context

                let ts = headerParts.count >= 1 ? headerParts[0] : "—"
                let levelStr = headerParts.count >= 2 ? headerParts[1] : ""
                let contextName: String? = {
                    guard headerParts.count >= 3 else { return nil }
                    let name = headerParts[2...].joined(separator: " ")
                    return (name == "SMAPI" || name == "game") ? nil : name
                }()

                let level: LogLevel
                switch levelStr.uppercased() {
                case "ERROR":  level = .error
                case "WARN":   level = .warning
                case "ALERT":  level = .warning
                case "INFO":   level = .info
                default:       level = .smapi  // TRACE, DEBUG, etc.
                }

                // Message = everything after "] "
                let msgStart = line.index(after: bracketEnd)
                let message = msgStart < line.endIndex
                    ? String(line[msgStart...]).trimmingCharacters(in: .whitespaces)
                    : ""

                if !message.isEmpty || contextName != nil {
                    var entry = LogEntry(timestamp: ts, message: message, level: level, source: .smapi)
                    entry.modName = contextName
                    entries.append(entry)
                }
            } else {
                // Continuation line — append to last entry's message
                let trimmed = line.trimmingCharacters(in: .whitespaces)
                guard !trimmed.isEmpty, !entries.isEmpty else { continue }
                let last = entries.removeLast()
                let combined = last.message.isEmpty ? trimmed : last.message + "\n" + trimmed
                var updated = LogEntry(timestamp: last.timestamp, message: combined, level: last.level, source: .smapi)
                updated.modName = last.modName
                entries.append(updated)
            }
        }

        if Thread.isMainThread {
            logEntries.append(contentsOf: entries)
        } else {
            DispatchQueue.main.async { self.logEntries.append(contentsOf: entries) }
        }
    }

    private var smapiLogPath: String {
        let homeDir = FileManager.default.homeDirectoryForCurrentUser.path
        return (homeDir as NSString).appendingPathComponent(
            ".config/StardewValley/ErrorLogs/SMAPI-latest.txt"
        )
    }

    func startSmapiLogWatcher() { loadSmapiLog() }
    func stopSmapiLogWatcher() {
        smapiLogTimer?.invalidate()
        smapiLogTimer = nil
        try? smapiLogFileHandle?.close()
        smapiLogFileHandle = nil
    }

    private func smapiLineLevel(_ line: String) -> LogLevel {
        if line.contains(" ERROR ") || line.contains("[ERROR") { return .error }
        if line.contains(" WARN ")  || line.contains("[WARN")  { return .warning }
        if line.contains(" ALERT ") { return .warning }
        return .smapi
    }
    
    func showModal(message: String) {
        self.alertMessage = message
        self.showAlert = true
    }
    
    // MARK: - Saves
    func reloadSaves() {
        self.saves = SaveManager.shared.fetchSaves()
    }
    
    func editSave(info: SaveGameInfo, newName: String, newFarm: String, newFav: String, newMoney: Int, newMaxHealth: Int, newMaxStamina: Int, newGoldenWalnuts: Int, newQiGems: Int, newClubCoins: Int) {
        let success = SaveManager.shared.updateSave(info: info, newName: newName, newFarm: newFarm, newFav: newFav, newMoney: newMoney, newMaxHealth: newMaxHealth, newMaxStamina: newMaxStamina, newGoldenWalnuts: newGoldenWalnuts, newQiGems: newQiGems, newClubCoins: newClubCoins)
        if success {
            reloadSaves()
            showModal(message: L(L10n.VM.saveSuccess))
        } else {
            showModal(message: L(L10n.VM.saveError))
        }
    }
    
    func deleteSave(info: SaveGameInfo) {
        if SaveManager.shared.deleteSave(info: info) {
            reloadSaves()
            showModal(message: L(L10n.VM.deleteSaveSuccess))
        } else {
            showModal(message: L(L10n.VM.deleteSaveError))
        }
    }
    
    var savesHierarchy: [SaveNode] {
        let saveNames = Set(saves.map(\.folderName))
        
        func getParentFolderName(for folderName: String) -> String? {
            var candidate = folderName
            while let range = candidate.range(of: "_", options: .backwards) {
                candidate = String(candidate[..<range.lowerBound])
                if saveNames.contains(candidate) {
                    return candidate
                }
            }
            return nil
        }
        
        func sortedNodes(_ nodes: [SaveNode]) -> [SaveNode] {
            nodes
                .map { SaveNode(info: $0.info, children: sortedNodes($0.children)) }
                .sorted { a, b in
                    switch saveSortOption {
                    case .name:
                        return a.info.playerName.localizedCaseInsensitiveCompare(b.info.playerName) == .orderedAscending
                    case .lastPlayed:
                        return a.info.lastModified > b.info.lastModified
                    case .money:
                        return a.info.money > b.info.money
                    }
                }
        }
        
        var childrenByParent: [String: [SaveGameInfo]] = [:]
        var rootSaves: [SaveGameInfo] = []
        
        for save in saves {
            if let parentFolderName = getParentFolderName(for: save.folderName) {
                childrenByParent[parentFolderName, default: []].append(save)
            } else {
                rootSaves.append(save)
            }
        }
        
        func buildNode(for save: SaveGameInfo) -> SaveNode {
            let children = childrenByParent[save.folderName, default: []].map { buildNode(for: $0) }
            return SaveNode(info: save, children: children)
        }
        
        var roots = rootSaves.map { buildNode(for: $0) }
        
        // Apply tag filter
        if !saveFilterTag.isEmpty {
            roots = roots.filter { node in
                let tag = SaveNotesStore.shared.note(for: node.info.folderName).tag
                return tag == saveFilterTag
            }
        }
        
        roots = sortedNodes(roots)
        
        return roots
    }
    
    var availableFilterTags: [String] {
        let allTags = saves.compactMap { SaveNotesStore.shared.note(for: $0.folderName).tag }.filter { !$0.isEmpty }
        return Array(Set(allTags)).sorted()
    }
    
    func setAvatar(forSave folderName: String, iconPath: String) {
        let note = SaveNotesStore.shared.note(for: folderName)
        SaveNotesStore.shared.setNote(for: folderName, tag: note.tag, note: note.note, customIconPath: iconPath)
        objectWillChange.send()
    }
    
    func selectCustomAvatar(forSave folderName: String, completion: ((String) -> Void)? = nil) {
        #if canImport(AppKit)
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.png, .jpeg, .gif]
        panel.allowsMultipleSelection = false
        panel.canChooseDirectories = false
        panel.title = L(L10n.Saves.avatarPanelTitle)
        if panel.runModal() == .OK, let url = panel.url {
            // Copy to app support dir to prevent broken paths
            let supportDir = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
                .appendingPathComponent("StarHubTH/Avatars", isDirectory: true)
            try? FileManager.default.createDirectory(at: supportDir, withIntermediateDirectories: true)
            let destURL = supportDir.appendingPathComponent("\(folderName)_\(url.lastPathComponent)")
            try? FileManager.default.copyItem(at: url, to: destURL)
            setAvatar(forSave: folderName, iconPath: destURL.path)
            completion?(destURL.path)
        }
        #endif
    }
    
    func duplicateSave(info: SaveGameInfo, newName: String, newFarm: String) {
        if SaveManager.shared.duplicateSave(info: info, newName: newName, newFarm: newFarm) {
            reloadSaves()
            showModal(message: L(L10n.VM.duplicateSaveSuccess))
        } else {
            showModal(message: L(L10n.VM.duplicateSaveError))
        }
    }
    
    func openSaveInFinder(info: SaveGameInfo) {
        SaveManager.shared.openSaveInFinder(info: info)
    }

    // MARK: - Backup Timeline

    func listBackups(for info: SaveGameInfo) -> [SaveBackup] {
        SaveManager.shared.listBackups(for: info)
    }

    func createBackup(info: SaveGameInfo) -> Bool {
        SaveManager.shared.backupSave(info: info)
    }
    
    func branchFromBackup(backup: SaveBackup, newName: String, newFarm: String) -> Bool {
        if SaveManager.shared.branchFromBackup(backup: backup, newName: newName, newFarm: newFarm) {
            reloadSaves()
            showModal(message: L(L10n.VM.branchSuccess))
            return true
        } else {
            showModal(message: L(L10n.VM.branchError))
            return false
        }
    }

    func restoreBackup(backup: SaveBackup, info: SaveGameInfo) {
        if SaveManager.shared.restoreBackup(backup: backup, info: info) {
            reloadSaves()
            viewingSaveTimeline = nil
            editingSave = nil
            showModal(message: L(L10n.VM.restoreSuccess))
        } else {
            showModal(message: L(L10n.VM.restoreError))
        }
    }

    func deleteBackup(_ backup: SaveBackup) -> Bool {
        SaveManager.shared.deleteBackup(backup)
    }

    // MARK: - Save Notes

    func getNote(for folderName: String) -> SaveNote {
        SaveNotesStore.shared.note(for: folderName)
    }

    func setNote(for folderName: String, tag: String, note: String) {
        // Preserve existing customIconPath
        let existing = SaveNotesStore.shared.note(for: folderName)
        SaveNotesStore.shared.setNote(for: folderName, tag: tag, note: note, customIconPath: existing.customIconPath)
        objectWillChange.send()
    }

    // MARK: - Backup & Management
    func backupAllSaves() {
        let home = NSHomeDirectory()
        let savesDir = "\(home)/.config/StardewValley/Saves"
        let desktopDir = "\(home)/Desktop"
        let timestamp = DateFormatter.localizedString(from: Date(), dateStyle: .short, timeStyle: .medium).replacingOccurrences(of: "/", with: "-").replacingOccurrences(of: ":", with: "")
        let zipPath = "\(desktopDir)/StardewSaves_Backup_\(timestamp).zip"
        
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        process.arguments = ["-r", zipPath, "."]
        process.currentDirectoryURL = URL(fileURLWithPath: savesDir)
        
        do {
            try process.run()
            process.waitUntilExit()
            if process.terminationStatus == 0 {
                showModal(message: String(format: L(L10n.VM.backupSavesSuccess), zipPath))
            } else {
                showModal(message: L(L10n.VM.zipSavesError))
            }
        } catch {
            showModal(message: L(L10n.VM.cannotRunZip))
        }
    }
    
    func backupAllMods() {
        guard !gameDir.isEmpty else {
            showModal(message: L(L10n.Settings.gameDirNotSet))
            return
        }
        let modsDir = (gameDir as NSString).appendingPathComponent("Mods")
        let home = NSHomeDirectory()
        let desktopDir = "\(home)/Desktop"
        let timestamp = DateFormatter.localizedString(from: Date(), dateStyle: .short, timeStyle: .medium).replacingOccurrences(of: "/", with: "-").replacingOccurrences(of: ":", with: "")
        let zipPath = "\(desktopDir)/StardewMods_Backup_\(timestamp).zip"
        
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/zip")
        process.arguments = ["-r", zipPath, "."]
        process.currentDirectoryURL = URL(fileURLWithPath: modsDir)
        
        do {
            try process.run()
            process.waitUntilExit()
            if process.terminationStatus == 0 {
                showModal(message: String(format: L(L10n.VM.backupModsSuccess), zipPath))
            } else {
                showModal(message: L(L10n.VM.zipModsError))
            }
        } catch {
            showModal(message: L(L10n.VM.cannotRunZip))
        }
    }
    
    func cleanDisabledMods() {
        guard !gameDir.isEmpty else { return }
        let disabledModsPath = (gameDir as NSString).appendingPathComponent("Mods_disabled")
        do {
            if FileManager.default.fileExists(atPath: disabledModsPath) {
                try FileManager.default.removeItem(atPath: disabledModsPath)
                showModal(message: L(L10n.VM.cleanModsSuccess))
                self.scanMods()
            } else {
                showModal(message: L(L10n.VM.cleanModsNotFound))
            }
        } catch {
            showModal(message: String(format: L(L10n.VM.cleanModsError), error.localizedDescription))
        }
    }
    
    // MARK: - Thai Translation Hub Logic
    
    func fetchThaiTranslations() {
        guard let url = URL(string: "https://raw.githubusercontent.com/AppleBoiy/stardew-thai-translations/main/README.md") else { return }
        
        URLSession.shared.dataTask(with: url) { data, response, error in
            guard let data = data, let content = String(data: data, encoding: .utf8) else { return }
            
            var newTranslations: [ThaiTranslationMod] = []
            let lines = content.components(separatedBy: .newlines)
            var inTable = false
            
            for line in lines {
                if line.starts(with: "| ชื่อม็อด") {
                    inTable = true
                    continue
                }
                if inTable && line.starts(with: "| :---") { continue }
                if inTable && line.starts(with: "|") {
                    let parts = line.components(separatedBy: "|").map { $0.trimmingCharacters(in: .whitespaces) }
                    if parts.count >= 6 {
                        let rawName = parts[1] // **[[CP] Additional Farm Cave](https://...)**
                        var cleanName = rawName.replacingOccurrences(of: "**", with: "")
                        var url = ""
                        
                        // Use regex to extract name and URL: [Name](URL)
                        let pattern = "\\[(.*?)\\]\\((.*?)\\)"
                        if let regex = try? NSRegularExpression(pattern: pattern, options: []),
                           let match = regex.firstMatch(in: cleanName, options: [], range: NSRange(location: 0, length: cleanName.utf16.count)) {
                            if let nameRange = Range(match.range(at: 1), in: cleanName) {
                                let extractedName = String(cleanName[nameRange])
                                if let urlRange = Range(match.range(at: 2), in: cleanName) {
                                    url = String(cleanName[urlRange])
                                }
                                cleanName = extractedName
                            }
                        }
                        
                        let author = parts[2]
                        let version = parts[3]
                        let status = parts[4]
                        
                        let rawNexus = parts[5]
                        var nexusUrl = ""
                        if let r1 = rawNexus.range(of: "("), let r2 = rawNexus.range(of: ")") {
                            nexusUrl = String(rawNexus[rawNexus.index(after: r1.lowerBound)..<r2.lowerBound])
                        }
                        
                        let mod = ThaiTranslationMod(
                            name: cleanName,
                            author: author,
                            version: version,
                            status: status,
                            url: url,
                            nexusUrl: nexusUrl,
                            isInstalled: false,
                            isOriginalModInstalled: false
                        )
                        newTranslations.append(mod)
                    }
                } else if inTable && line.isEmpty {
                    inTable = false
                }
            }
            
            DispatchQueue.main.async {
                self.thaiTranslations = newTranslations
                self.evaluateThaiTranslationStatus()
            }
        }.resume()
    }
    
    func evaluateThaiTranslationStatus() {
        guard !gameDir.isEmpty else { return }
        let fm = FileManager.default
        let modsDir = (gameDir as NSString).appendingPathComponent("Mods")
        
        for i in 0..<thaiTranslations.count {
            // Very simple check: does any mod folder contain an i18n/th.json?
            // AND does the folder name sort of match the mod name?
            let nameToCheck = thaiTranslations[i].name.replacingOccurrences(of: "[CP]", with: "").trimmingCharacters(in: .whitespaces)
            var foundTranslation = false
            var foundOriginal = false
            for mod in mods {
                if mod.name.localizedCaseInsensitiveContains(nameToCheck) || nameToCheck.localizedCaseInsensitiveContains(mod.name) {
                    foundOriginal = true
                    let thJsonPath = (modsDir as NSString).appendingPathComponent("\(mod.folderName)/i18n/th.json")
                    let cpThJsonPath = (modsDir as NSString).appendingPathComponent("\(mod.folderName)/[CP] \(mod.folderName)/i18n/th.json") // Handle nested [CP]
                    if fm.fileExists(atPath: thJsonPath) || fm.fileExists(atPath: cpThJsonPath) {
                        foundTranslation = true
                    }
                }
            }
            thaiTranslations[i].isOriginalModInstalled = foundOriginal
            thaiTranslations[i].isInstalled = foundTranslation
        }
        
        // Sort installed mods first, then alphabetically
        thaiTranslations.sort { mod1, mod2 in
            if mod1.isInstalled != mod2.isInstalled {
                return mod1.isInstalled
            }
            return mod1.name.localizedStandardCompare(mod2.name) == .orderedAscending
        }
    }
    
    func installThaiTranslation(mod: ThaiTranslationMod) {
        guard !gameDir.isEmpty else { return }
        
        let modsDir = (gameDir as NSString).appendingPathComponent("Mods")
        let zipName = "\(mod.name.replacingOccurrences(of: "[CP] ", with: "")) - Thai Translation.zip"
        let encodedZipName = zipName.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? zipName
        let downloadUrlStr = "https://raw.githubusercontent.com/AppleBoiy/stardew-thai-translations/main/bundles/\(encodedZipName)"
        
        guard let downloadUrl = URL(string: downloadUrlStr) else {
            showModal(message: L(L10n.VM.urlError))
            return
        }
        
        showModal(message: String(format: L(L10n.VM.downloadingTranslation), mod.name))
        
        let task = URLSession.shared.downloadTask(with: downloadUrl) { localUrl, response, error in
            if let error = error {
                DispatchQueue.main.async {
                    self.showModal(message: String(format: self.L(L10n.VM.downloadFailed), error.localizedDescription))
                }
                return
            }
            
            guard let localUrl = localUrl else { return }
            let process = Process()
            process.executableURL = URL(fileURLWithPath: "/usr/bin/unzip")
            process.arguments = ["-o", localUrl.path, "-d", modsDir]
            
            do {
                try process.run()
                process.waitUntilExit()
                
                DispatchQueue.main.async {
                    if process.terminationStatus == 0 {
                        self.showModal(message: String(format: self.L(L10n.VM.installThaiSuccess), mod.name))
                        self.evaluateThaiTranslationStatus()
                    } else {
                        self.showModal(message: self.L(L10n.VM.unzipError))
                    }
                }
            } catch {
                DispatchQueue.main.async {
                    self.showModal(message: String(format: self.L(L10n.VM.unzipFailed), error.localizedDescription))
                }
            }
        }
        task.resume()
    }
    
    func openSavesFolder() {
        let home = NSHomeDirectory()
        let savesDir = URL(fileURLWithPath: "\(home)/.config/StardewValley/Saves")
        NSWorkspace.shared.open(savesDir)
    }
    
    // MARK: - Mod Profiles
    func loadProfiles() {
        if let data = UserDefaults.standard.data(forKey: "modProfiles"),
           let profiles = try? JSONDecoder().decode([ModProfile].self, from: data) {
            self.modProfiles = profiles
        } else {
            self.modProfiles = []
        }
        
        if let activeIdStr = UserDefaults.standard.string(forKey: "activeProfileId"),
           let activeId = UUID(uuidString: activeIdStr) {
            self.activeProfileId = activeId
        }
    }
    
    func saveProfiles() {
        if let data = try? JSONEncoder().encode(modProfiles) {
            UserDefaults.standard.set(data, forKey: "modProfiles")
        }
        if let activeId = activeProfileId {
            UserDefaults.standard.set(activeId.uuidString, forKey: "activeProfileId")
        } else {
            UserDefaults.standard.removeObject(forKey: "activeProfileId")
        }
    }
    
    func createProfile(name: String) {
        // Snapshot the currently enabled mods into the new profile
        let currentEnabledIds = mods
            .flatMap { mod -> [String] in
                if mod.isGroup, let children = mod.children {
                    return children.filter { $0.isEnabled }.map { $0.uniqueId }
                }
                return mod.isEnabled ? [mod.uniqueId] : []
            }
            .filter { !$0.isEmpty }

        let newProfile = ModProfile(name: name, enabledModIds: currentEnabledIds)
        modProfiles.append(newProfile)
        saveProfiles()
        // Do NOT applyProfile here — just save so the user can edit it first
        activeProfileId = newProfile.id
        saveProfiles()
    }
    
    func deleteProfile(id: UUID) {
        modProfiles.removeAll { $0.id == id }
        if activeProfileId == id {
            activeProfileId = nil
        }
        saveProfiles()
    }
    
    func updateProfile(id: UUID, newName: String, enabledModIds: [String]) {
        if let index = modProfiles.firstIndex(where: { $0.id == id }) {
            modProfiles[index].name = newName
            modProfiles[index].enabledModIds = enabledModIds
            saveProfiles()

            // If this is the active profile, apply the new mod selection to the filesystem
            if activeProfileId == id {
                applyProfileToFilesystem(profile: modProfiles[index])
            }
        }
    }

    func applyProfile(id: UUID?) {
        guard let id = id, let profile = modProfiles.first(where: { $0.id == id }) else {
            activeProfileId = nil
            saveProfiles()
            return
        }

        // If already active, just sync stored list from current filesystem (no file moves)
        if activeProfileId == id {
            syncActiveProfileIds()
            return
        }

        activeProfileId = id
        saveProfiles()
        applyProfileToFilesystem(profile: profile)
        self.log(String(format: L(L10n.VM.switchProfile), profile.name))
    }

    /// Actually move mod files to match the given profile's enabledModIds.
    private func applyProfileToFilesystem(profile: ModProfile) {
        let fm = FileManager.default
        let modsPath = (gameDir as NSString).appendingPathComponent("Mods")
        let disabledModsPath = (gameDir as NSString).appendingPathComponent("Mods_disabled")

        // Check whether a mod (or any of its children) is covered by the profile's enabled list
        func isCoveredByProfile(_ mod: ModItem) -> Bool {
            if mod.isGroup, let children = mod.children {
                return children.contains { profile.enabledModIds.contains($0.uniqueId) }
            }
            return profile.enabledModIds.contains(mod.uniqueId)
        }

        // Disable mods not in profile
        for mod in mods.filter({ $0.isEnabled }) {
            if !isCoveredByProfile(mod) {
                let src = (modsPath as NSString).appendingPathComponent(mod.folderName)
                let dst = (disabledModsPath as NSString).appendingPathComponent(mod.folderName)
                try? fm.createDirectory(atPath: (dst as NSString).deletingLastPathComponent,
                                        withIntermediateDirectories: true, attributes: nil)
                try? fm.moveItem(atPath: src, toPath: dst)
            }
        }

        // Enable mods in profile
        for mod in mods.filter({ !$0.isEnabled }) {
            if isCoveredByProfile(mod) {
                let src = (disabledModsPath as NSString).appendingPathComponent(mod.folderName)
                let dst = (modsPath as NSString).appendingPathComponent(mod.folderName)
                try? fm.createDirectory(atPath: (dst as NSString).deletingLastPathComponent,
                                        withIntermediateDirectories: true, attributes: nil)
                try? fm.moveItem(atPath: src, toPath: dst)
            }
        }

        self.scanMods()
        self.syncActiveProfileIds()
    }

    /// Compute which uniqueIds should be added/removed when toggling a mod in a profile,
    /// using the same chain logic as toggleMod. Works on an in-memory set (no file I/O).
    /// - Parameters:
    ///   - mod: The mod being toggled (can be a group or single mod)
    ///   - enable: true = enabling, false = disabling
    ///   - currentEnabled: the current set of enabled uniqueIds in the profile
    /// - Returns: A new set with the chain applied
    func applyChainToSet(mod: ModItem, enable: Bool, currentEnabled: Set<String>) -> Set<String> {
        var result = currentEnabled

        // Build helpers identical to toggleMod
        func getTopLevelMod(for uniqueId: String) -> ModItem? {
            for m in mods {
                if !m.isGroup && m.uniqueId.caseInsensitiveCompare(uniqueId) == .orderedSame { return m }
                if m.isGroup, let children = m.children,
                   children.contains(where: { $0.uniqueId.caseInsensitiveCompare(uniqueId) == .orderedSame }) { return m }
            }
            return nil
        }

        func getDependencies(for topMod: ModItem) -> [ModDependency] {
            if topMod.isGroup, let children = topMod.children { return children.flatMap { $0.dependencies } }
            return topMod.dependencies
        }

        // Collect all uniqueIds provided by the target mod (single or group)
        func providedIds(for topMod: ModItem) -> [String] {
            if topMod.isGroup, let children = topMod.children { return children.map { $0.uniqueId } }
            return [topMod.uniqueId]
        }

        // All top-level mods to process — for a group, start with the group itself
        let startingMod = mod.isGroup ? mod : (getTopLevelMod(for: mod.uniqueId) ?? mod)
        let startingIds = providedIds(for: startingMod)

        if enable {
            // Enable starting mod's ids
            startingIds.forEach { result.insert($0) }

            if chainToggleDependencies {
                // BFS: enable all required dependencies
                var queue = [startingMod]
                var visited = Set<String>([startingMod.folderName])
                while !queue.isEmpty {
                    let current = queue.removeFirst()
                    for dep in getDependencies(for: current) where dep.isRequired {
                        if let depMod = getTopLevelMod(for: dep.uniqueId), !visited.contains(depMod.folderName) {
                            visited.insert(depMod.folderName)
                            providedIds(for: depMod).forEach { result.insert($0) }
                            queue.append(depMod)
                        }
                    }
                }
            }
        } else {
            // Disable starting mod's ids
            startingIds.forEach { result.remove($0) }

            if chainToggleDependencies {
                // BFS: disable any mod that requires the now-disabled mod
                var queue = [startingMod]
                var visited = Set<String>([startingMod.folderName])
                while !queue.isEmpty {
                    let current = queue.removeFirst()
                    let currentIds = providedIds(for: current)
                    for candidate in mods {
                        guard !visited.contains(candidate.folderName) else { continue }
                        let candidateDeps = getDependencies(for: candidate)
                        let requiresCurrent = candidateDeps.contains { dep in
                            dep.isRequired && currentIds.contains { $0.caseInsensitiveCompare(dep.uniqueId) == .orderedSame }
                        }
                        if requiresCurrent {
                            visited.insert(candidate.folderName)
                            providedIds(for: candidate).forEach { result.remove($0) }
                            queue.append(candidate)
                        }
                    }
                }
            }
        }

        return result
    }
    /// Call this after any toggleMod so the profile stays up to date.
    func syncActiveProfileIds() {
        guard let id = activeProfileId,
              let index = modProfiles.firstIndex(where: { $0.id == id }) else { return }

        let actualEnabledIds = mods
            .flatMap { mod -> [String] in
                if mod.isGroup, let children = mod.children {
                    return children.filter { $0.isEnabled }.map { $0.uniqueId }
                }
                return mod.isEnabled ? [mod.uniqueId] : []
            }
            .filter { !$0.isEmpty }

        modProfiles[index].enabledModIds = actualEnabledIds
        saveProfiles()
    }
}
