import Foundation

/// Sévérité d'une ligne de journal, telle que SMAPI la nomme.
///
/// **Aucune présentation ici** : la couleur et l'icône vivent dans
/// `LogLevel+Presentation.swift`, côté vue. C'est ce qui permet à ce type — et
/// donc à `LogEntry` — de vivre dans `StarHubTHCore`, où il devient testable ;
/// un `Color` SwiftUI dans le modèle l'en excluait.
public enum LogLevel: String, CaseIterable, Sendable {
    case info    = "INFO"
    case warning = "WARN"
    case error   = "ERROR"
    case trace   = "TRACE"   // TRACE/DEBUG lines from the SMAPI log
}

/// D'où vient la ligne : de StarHubFR, ou du journal de SMAPI.
public enum LogSource: Sendable {
    case app    // generated by StarHubFR itself
    case smapi  // loaded from SMAPI-latest.txt
}

public struct LogEntry: Identifiable, Sendable {
    public let id = UUID()
    public let timestamp: String
    public let message: String
    public let level: LogLevel
    public let source: LogSource
    /// Le mod auquel la ligne est imputée, quand il a pu être déterminé — soit
    /// par le crochet de source, soit par le préfixe du message (voir
    /// `LogNoise.modNamePrefix(in:)`).
    public var modName: String? = nil

    public init(timestamp: String, message: String, level: LogLevel,
                source: LogSource, modName: String? = nil) {
        self.timestamp = timestamp
        self.message = message
        self.level = level
        self.source = source
        self.modName = modName
    }

    /// The plain-text line used by both "copy all" and "copy line" in
    /// LogsView, so the two can't format entries differently. Includes the
    /// source (StarHubFR vs SMAPI) and the mod name so the origin and context
    /// survive the copy (B3 — previously only timestamp/level/message).
    public var formattedLine: String {
        let sourceLabel = source == .app ? "StarHubFR" : "SMAPI"
        let mod = modName.map { "\($0): " } ?? ""
        return "[\(timestamp)] [\(sourceLabel)] [\(level.rawValue)] \(mod)\(message)"
    }
}
