import Foundation

/// L'assembly de test d'A5-T6, produit par **le vrai producteur**
/// (`dotnet build -c Release`, SDK 10, net8.0, `Deterministic`) et non écrit
/// à la main. Source compilée :
///
/// ```csharp
/// using System;
/// namespace HiddenRefs.Core
/// {
///     public class Outer
///     {
///         public class Inner { public class Deepest { } }
///     }
///     public static class Lookups
///     {
///         public static object[] Names() => new object[]
///         {
///             Type.GetType("ContentPatcher.Framework.PatchManager"),
///             Type.GetType("SpaceCore.Skills+Skill+Profession, SpaceCore"),
///             "Pathoschild.Stardew.Automate.Framework.MachineGroup:GetMachines",
///             "  FarmTypeManager.ModEntry+Utility:SpawnForage  ",
///             "ValleyBonds.IsekaiBonds_RiftEel",
///             "ChestsAnywhere.pdb",
///             "not a type name",
///             "ModEntry",
///             "HiddenRefs.Core.Outer+Inner",
///             "Généré.Type",
///         };
///     }
/// }
/// ```
///
/// Oracle (dnfile, 2026-10-08) : tas `#US` = les dix littéraux ci-dessus dans
/// l'ordre ; `TypeDef` = `<Module>`, `HiddenRefs.Core.Lookups`,
/// `HiddenRefs.Core.Outer`, `HiddenRefs.Core.Outer+Inner`,
/// `HiddenRefs.Core.Outer+Inner+Deepest`.
enum HiddenRefsAssembly {
    static var bytes: [UInt8] { Array(Data(base64Encoded: base64)!) }

    static let base64 =
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgB" +
        "TM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAFUj48QAAAAAAAAAAOAA" +
        "IiALATAAAAoAAAAGAAAAAAAACikAAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUA" +
        "ABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAALgoAABPAAAAAEAAADADAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAACcKAAA" +
        "HAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAA" +
        "AC50ZXh0AAAAEAkAAAAgAAAACgAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAADADAAAAQAAAAAQAAAAMAAAAAAAAAAAAAAAA" +
        "AABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAEAAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAADsKAAAAAAAAEgAAAAC" +
        "AAUA2CAAAMQHAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4CKAwAAAoq" +
        "EzAEAGMAAAAAAAAAHwqNDQAAASUWcgEAAHAoDQAACqIlF3JNAABwKA0AAAqiJRhypwAAcKIlGXInAQBwoiUacokBAHCiJRtyyQEA" +
        "cKIlHHLvAQBwoiUdcg8CAHCiJR5yIQIAcKIlHwlyWQIAcKIqHgIoDAAACioeAigMAAAKKgBCU0pCAQABAAAAAAAMAAAAdjQuMC4z" +
        "MDMxOQAAAAAFAGwAAADcAQAAI34AAEgCAAAgAgAAI1N0cmluZ3MAAAAAaAQAAHQCAAAjVVMA3AYAABAAAAAjR1VJRAAAAOwGAADY" +
        "AAAAI0Jsb2IAAAAAAAAAAgAAAUcUAAAJAgAAAPoBMwAWAAABAAAADgAAAAUAAAAEAAAADQAAAAsAAAABAAAAAQAAAAIAAAAAAHkB" +
        "AQAAAAAABgDvAMYBBgBBAcYBBgAxALMBDwDmAQAABgBcAF8BBgAoAY8BBgC4AI8BBgB1AI8BBgCSAI8BBgAPAY8BBgBFAI8BBgDX" +
        "AMYBBgAOAogBBgAcAIgBAAAAAAEAAAAAAAEAAQABABAApwEhADUAAQABAIEBEAAGAiEANQABAAIAAgAQAKEBAAA1AAEAAwACABAA" +
        "FQIAADUAAQAEAFAgAAAAAIYYrQEGAAEAWCAAAAAAlgD1ASQAAQDHIAAAAACGGK0BBgABAM8gAAAAAIYYrQEGAAEACQCtAQEAEQCt" +
        "AQYAGQCtAQoAKQCtARAAMQCtARAAOQCtARAAQQCtARAASQCtARAAUQCtARAAWQCtARAAYQCtAQEAaQCtAQYAcQAZABUAJwBbAM0A" +
        "LgALACkALgATADIALgAbAFEALgAjAFoALgArAJgALgAzAKgALgA7ALUALgBDAMIALgBLAJgALgBTAJgABIAAAAEAAAAAAAAAAAAA" +
        "AAAA+wEAAAgAAAAAAAAAAAAAABsACgAAAAAABAACAAUABAAAAAA8TW9kdWxlPgBTeXN0ZW0uUnVudGltZQBHZXRUeXBlAEhpZGRl" +
        "blJlZnMuQ29yZQBEZWJ1Z2dhYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmli" +
        "dXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlJbmZvcm1hdGlvbmFsVmVyc2lvbkF0dHJpYnV0ZQBBc3Nl" +
        "bWJseUNvbmZpZ3VyYXRpb25BdHRyaWJ1dGUAUmVmU2FmZXR5UnVsZXNBdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0" +
        "dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmls" +
        "aXR5QXR0cmlidXRlAFN5c3RlbS5SdW50aW1lLlZlcnNpb25pbmcASGlkZGVuUmVmcy5kbGwAU3lzdGVtAFN5c3RlbS5SZWZsZWN0" +
        "aW9uAElubmVyAE91dGVyAC5jdG9yAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzAERl" +
        "YnVnZ2luZ01vZGVzAE5hbWVzAEhpZGRlblJlZnMATG9va3VwcwBPYmplY3QARGVlcGVzdAAAAAAAS0MAbwBuAHQAZQBuAHQAUABh" +
        "AHQAYwBoAGUAcgAuAEYAcgBhAG0AZQB3AG8AcgBrAC4AUABhAHQAYwBoAE0AYQBuAGEAZwBlAHIAAFlTAHAAYQBjAGUAQwBvAHIA" +
        "ZQAuAFMAawBpAGwAbABzACsAUwBrAGkAbABsACsAUAByAG8AZgBlAHMAcwBpAG8AbgAsACAAUwBwAGEAYwBlAEMAbwByAGUAAH9Q" +
        "AGEAdABoAG8AcwBjAGgAaQBsAGQALgBTAHQAYQByAGQAZQB3AC4AQQB1AHQAbwBtAGEAdABlAC4ARgByAGEAbQBlAHcAbwByAGsA" +
        "LgBNAGEAYwBoAGkAbgBlAEcAcgBvAHUAcAA6AEcAZQB0AE0AYQBjAGgAaQBuAGUAcwAAYSAAIABGAGEAcgBtAFQAeQBwAGUATQBh" +
        "AG4AYQBnAGUAcgAuAE0AbwBkAEUAbgB0AHIAeQArAFUAdABpAGwAaQB0AHkAOgBTAHAAYQB3AG4ARgBvAHIAYQBnAGUAIAAgAAA/" +
        "VgBhAGwAbABlAHkAQgBvAG4AZABzAC4ASQBzAGUAawBhAGkAQgBvAG4AZABzAF8AUgBpAGYAdABFAGUAbAAAJUMAaABlAHMAdABz" +
        "AEEAbgB5AHcAaABlAHIAZQAuAHAAZABiAAAfbgBvAHQAIABhACAAdAB5AHAAZQAgAG4AYQBtAGUAABFNAG8AZABFAG4AdAByAHkA" +
        "ADdIAGkAZABkAGUAbgBSAGUAZgBzAC4AQwBvAHIAZQAuAE8AdQB0AGUAcgArAEkAbgBuAGUAcgAAF0cA6QBuAOkAcgDpAC4AVAB5" +
        "AHAAZQABAAAAQ19nCV6ojk6ClYKnbMbwlQAEIAEBCAMgAAEFIAEBEREEIAEBDgUAARI5DgiwP19/EdUKOgQAAB0cCAEACAAAAAAA" +
        "HgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQgBAAIAAAAAAD0BABguTkVUQ29yZUFwcCxWZXJzaW9uPXY4LjABAFQOFEZy" +
        "YW1ld29ya0Rpc3BsYXlOYW1lCC5ORVQgOC4wDwEACkhpZGRlblJlZnMAAAwBAAdSZWxlYXNlAAAMAQAHMS4wLjAuMAAACgEABTEu" +
        "MC4wAAAIAQALAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAADgKAAAAAAAAAAAAAD6KAAAACAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAA7CgAAAAAAAAAAAAAAABfQ29yRGxsTWFpbgBtc2NvcmVlLmRsbAAAAAAA/yUAIAAQAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAANQC" +
        "AAAAAAAAAAAAANQCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/" +
        "AAAAAAAAAAQAAAACAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMA" +
        "bABhAHQAaQBvAG4AAAAAAAAAsAQ0AgAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAAAQAgAAAQAwADAAMAAwADAANABi" +
        "ADAAAAA2AAsAAQBDAG8AbQBwAGEAbgB5AE4AYQBtAGUAAAAAAEgAaQBkAGQAZQBuAFIAZQBmAHMAAAAAAD4ACwABAEYAaQBsAGUA" +
        "RABlAHMAYwByAGkAcAB0AGkAbwBuAAAAAABIAGkAZABkAGUAbgBSAGUAZgBzAAAAAAAwAAgAAQBGAGkAbABlAFYAZQByAHMAaQBv" +
        "AG4AAAAAADEALgAwAC4AMAAuADAAAAA+AA8AAQBJAG4AdABlAHIAbgBhAGwATgBhAG0AZQAAAEgAaQBkAGQAZQBuAFIAZQBmAHMA" +
        "LgBkAGwAbAAAAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAEYADwABAE8AcgBpAGcAaQBuAGEAbABG" +
        "AGkAbABlAG4AYQBtAGUAAABIAGkAZABkAGUAbgBSAGUAZgBzAC4AZABsAGwAAAAAADYACwABAFAAcgBvAGQAdQBjAHQATgBhAG0A" +
        "ZQAAAAAASABpAGQAZABlAG4AUgBlAGYAcwAAAAAAMAAGAAEAUAByAG8AZAB1AGMAdABWAGUAcgBzAGkAbwBuAAAAMQAuADAALgAw" +
        "AAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAADDkAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
}
